name: Bug Report
description: Report a defect or regression so we can address it quickly.
title: "Bug: <summary>"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue. Please provide as much detail as possible so we can reproduce and fix it.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the problem in one sentence.
      placeholder: Item list does not refresh when switching categories
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How badly does this bug impact gameplay?
      options:
        - Critical (game breaking)
        - Major (core feature impacted)
        - Minor (workaround exists)
        - Cosmetic (visual or copy issue)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: Describe what you expected to happen.
      placeholder: The item list should refresh and display only the selected category.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: Describe what actually happened, including any error messages.
      placeholder: The item list always shows Weapons, regardless of the category selected.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a clear, ordered list of steps so we can reproduce the issue.
      placeholder: |
        1. Open the cheat menu
        2. Select the Ammo category
        3. Observe that the item list stays on Weapons
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Include mod version, game build, single/multiplayer, and any other relevant context.
      placeholder: |
        - Mod version: v1.0.2
        - Project Zomboid build: 41.78
        - Mode: Multiplayer
        - Other active mods: <list>
    validations:
      required: true

  - type: attachments
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Attach console logs, stack traces, or screenshots that help illustrate the problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else we should know? Links to related issues, save files, etc.
